# Generated by Django 4.1 on 2022-09-01 15:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiklatModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nama_diklat", models.CharField(max_length=255)),
                (
                    "golongan",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("Ia", "Ia"),
                            ("Ib", "Ib"),
                            ("Ic", "Ic"),
                            ("Id", "Id"),
                            ("IIa", "IIa"),
                            ("IIb", "IIb"),
                            ("IIc", "IIc"),
                            ("IId", "IId"),
                            ("IIIa", "IIIa"),
                            ("IIIb", "IIIb"),
                            ("IIIc", "IIIc"),
                            ("IIId", "IIId"),
                            ("IVa", "IVa"),
                            ("IVb", "IVb"),
                            ("IVc", "IVc"),
                            ("IVd", "IVd"),
                            ("IVe", "IVe"),
                        ],
                        max_length=200,
                    ),
                ),
                ("started_at", models.DateField(default=django.utils.timezone.now)),
                ("ended_at", models.DateField(default=django.utils.timezone.now)),
            ],
            options={"verbose_name_plural": "Diklat",},
        ),
        migrations.CreateModel(
            name="GolonganModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "golongan",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("Ia", "Ia"),
                            ("Ib", "Ib"),
                            ("Ic", "Ic"),
                            ("Id", "Id"),
                            ("IIa", "IIa"),
                            ("IIb", "IIb"),
                            ("IIc", "IIc"),
                            ("IId", "IId"),
                            ("IIIa", "IIIa"),
                            ("IIIb", "IIIb"),
                            ("IIIc", "IIIc"),
                            ("IIId", "IIId"),
                            ("IVa", "IVa"),
                            ("IVb", "IVb"),
                            ("IVc", "IVc"),
                            ("IVd", "IVd"),
                            ("IVe", "IVe"),
                        ],
                        max_length=200,
                    ),
                ),
            ],
            options={"verbose_name_plural": "Golongan",},
        ),
        migrations.CreateModel(
            name="PesertaModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nip", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=100)),
                (
                    "golongan",
                    models.CharField(
                        choices=[
                            ("Ia", "Ia"),
                            ("Ib", "Ib"),
                            ("Ic", "Ic"),
                            ("Id", "Id"),
                            ("IIa", "IIa"),
                            ("IIb", "IIb"),
                            ("IIc", "IIc"),
                            ("IId", "IId"),
                            ("IIIa", "IIIa"),
                            ("IIIb", "IIIb"),
                            ("IIIc", "IIIc"),
                            ("IIId", "IIId"),
                            ("IVa", "IVa"),
                            ("IVb", "IVb"),
                            ("IVc", "IVc"),
                            ("IVd", "IVd"),
                            ("IVe", "IVe"),
                        ],
                        default="IIIa",
                        max_length=5,
                    ),
                ),
                ("asal_instansi", models.CharField(max_length=100)),
                (
                    "diklat_id",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="diklat.diklatmodel",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Peserta",},
        ),
    ]
