# Generated by Django 4.1 on 2022-09-01 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("diklat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pesertamodel",
            name="diklat_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="diklat.diklatmodel",
            ),
        ),
    ]
