# Generated by Django 4.1 on 2022-09-05 13:53

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("diklat", "0002_alter_pesertamodel_diklat_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diklatmodel",
            name="golongan",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("I/a", "I/a"),
                    ("I/b", "I/b"),
                    ("I/c", "I/c"),
                    ("I/d", "I/d"),
                    ("II/a", "II/a"),
                    ("II/b", "II/b"),
                    ("II/c", "II/c"),
                    ("II/d", "II/d"),
                    ("III/a", "III/a"),
                    ("III/b", "III/b"),
                    ("III/c", "III/c"),
                    ("III/d", "III/d"),
                    ("IV/a", "IV/a"),
                    ("IV/b", "IV/b"),
                    ("IV/c", "IV/c"),
                    ("IV/d", "IV/d"),
                    ("IV/e", "IV/e"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="golonganmodel",
            name="golongan",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("I/a", "I/a"),
                    ("I/b", "I/b"),
                    ("I/c", "I/c"),
                    ("I/d", "I/d"),
                    ("II/a", "II/a"),
                    ("II/b", "II/b"),
                    ("II/c", "II/c"),
                    ("II/d", "II/d"),
                    ("III/a", "III/a"),
                    ("III/b", "III/b"),
                    ("III/c", "III/c"),
                    ("III/d", "III/d"),
                    ("IV/a", "IV/a"),
                    ("IV/b", "IV/b"),
                    ("IV/c", "IV/c"),
                    ("IV/d", "IV/d"),
                    ("IV/e", "IV/e"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="pesertamodel",
            name="golongan",
            field=models.CharField(
                choices=[
                    ("I/a", "I/a"),
                    ("I/b", "I/b"),
                    ("I/c", "I/c"),
                    ("I/d", "I/d"),
                    ("II/a", "II/a"),
                    ("II/b", "II/b"),
                    ("II/c", "II/c"),
                    ("II/d", "II/d"),
                    ("III/a", "III/a"),
                    ("III/b", "III/b"),
                    ("III/c", "III/c"),
                    ("III/d", "III/d"),
                    ("IV/a", "IV/a"),
                    ("IV/b", "IV/b"),
                    ("IV/c", "IV/c"),
                    ("IV/d", "IV/d"),
                    ("IV/e", "IV/e"),
                ],
                default="IIIa",
                max_length=5,
            ),
        ),
    ]
