# Generated by Django 4.1 on 2022-09-05 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diklat", "0003_alter_diklatmodel_golongan_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pesertamodel", old_name="asal_instansi", new_name="instansi",
        ),
    ]
