# Generated by Django 4.1 on 2022-09-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diklat", "0005_pesertamodel_jabatan"),
    ]

    operations = [
        migrations.AddField(
            model_name="diklatmodel",
            name="jabatan",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
