# Generated by Django 4.1 on 2022-09-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diklat", "0006_diklatmodel_jabatan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diklatmodel",
            name="jabatan",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
