# Generated by Django 4.1 on 2022-09-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diklat", "0007_alter_diklatmodel_jabatan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pesertamodel",
            name="jabatan",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
