# Generated by Django 4.1 on 2022-09-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diklat", "0008_alter_pesertamodel_jabatan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diklatmodel",
            name="jabatan",
            field=models.CharField(
                blank=True, help_text="test", max_length=100, null=True
            ),
        ),
    ]
