# Generated by Django 4.1 on 2022-09-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diklat", "0009_alter_diklatmodel_jabatan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diklatmodel",
            name="jabatan",
            field=models.CharField(
                blank=True,
                help_text="Boleh kosong. Jika syarat lebih dari 1, pisahkan dengan karakter koma (,). Contoh: Guru,Kepala Sekolah",
                max_length=100,
                null=True,
            ),
        ),
    ]
