# Generated by Django 4.1 on 2022-09-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diklat", "0012_alter_pesertamodel_nip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pesertamodel",
            name="nip",
            field=models.CharField(max_length=30),
        ),
    ]
